// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FineCodeCoverage
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFCCPackageString = "4e91ba47-cd42-42bc-b92e-3c4355d2eb5f";
        public static Guid guidFCCPackage = new Guid(guidFCCPackageString);

        public const string guidOutputToolWindowPackageCmdSetString = "d58a999f-4a1b-42df-839a-cb31a0a4fed7";
        public static Guid guidOutputToolWindowPackageCmdSet = new Guid(guidOutputToolWindowPackageCmdSetString);

        public const string guidOutputToolWindowCommandImageString = "297e101c-4afa-47b1-b382-087cfb4618b0";
        public static Guid guidOutputToolWindowCommandImage = new Guid(guidOutputToolWindowCommandImageString);

        public const string guidClearUICommandImageString = "8252a6d7-bcf3-4518-ae22-ad20ef8d4b63";
        public static Guid guidClearUICommandImage = new Guid(guidClearUICommandImageString);

        public const string guidImagesString = "0da4da8c-d4ce-4134-8d56-a33195833c0b";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ToolWindowToolbar = 0x1021;
        public const int ToolWindowToolbarGroup = 0x1022;
        public const int cmdidOutputToolWindowCommand = 0x00FF;
        public const int cmdidClearUICommand = 0x0100;
        public const int cmdidOpenCoberturaCommand = 0x0101;
        public const int cmdidOpenHotspotsCommand = 0x0102;
        public const int cmdidOpenFCCOutputPaneCommand = 0x0103;
        public const int cmdidOpenSettingsCommand = 0x0104;
        public const int cmdidMarketplaceRateAndReviewCommand = 0x0105;
        public const int cmdidOpenFCCGithubCommand = 0x0106;
        public const int cmdidNewIssueCommand = 0x0107;
        public const int cmdidOpenReadMeCommand = 0x0108;
        public const int cmdidToolWindow1Command = 0x1023;
        public const int outputToolWindowCommandImageIndex = 0x0001;
        public const int clearUICommandImageIndex = 0x0001;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}